<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSConsultaMicroMarketWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSConsultaMicroMarketWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSConsultaMicroMarketWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsconsultas/">
    <import location="http://localhost:33996/WSConsultaMicroMarket/WSConsultaMicroMarket?WSDL" namespace="http://wsconsultas/"/>
    <plnk:partnerLinkType name="WSConsultaMicroMarketLinkType">
        <plnk:role name="WSConsultaMicroMarketRole" portType="ns:WSConsultaMicroMarket"/>
    </plnk:partnerLinkType>
</definitions>
