<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSConsultaCustomerWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSConsultaCustomerWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSConsultaCustomerWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsconsultas/">
    <import location="http://localhost:33996/WSConsultaCustomer/WSConsultaCustomer?WSDL" namespace="http://wsconsultas/"/>
    <plnk:partnerLinkType name="WSConsultaCustomerLinkType">
        <plnk:role name="WSConsultaCustomerRole" portType="ns:WSConsultaCustomer"/>
    </plnk:partnerLinkType>
</definitions>
