<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSEnviosWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSEnviosWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSEnviosWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsenvios/">
    <import location="http://localhost:33996/WSEnvios/WSEnvios?WSDL" namespace="http://wsenvios/"/>
    <plnk:partnerLinkType name="WSEnviosLinkType">
        <plnk:role name="WSEnviosRole" portType="ns:WSEnvios"/>
    </plnk:partnerLinkType>
</definitions>
